development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  host: localhost
  pool: 5
  username: blog
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  host: localhost
  pool: 5
  username: blog
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  host: localhost
  pool: 5
  username: blog
  password: password
